catalog/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, re_path
from .views import *

urlpatterns = [
    path("", index, name="index"),
    path("consoles/", consoles, name="consoles"),
    path("makenews/", make_news, name="makenews"),
    path("consoles/<int:company_id>/", company_consoles, name="consoles1"),
    re_path(
        r"console/(?P<pk>\d+)$", ConsoleDetailView.as_view(), name="console-detail"
    ),
    ##re_path(r"news/(?P<pk>\d+)$", NewsDetailView.as_view(), name="news-detail"),
    re_path(r"news/(?P<pk>\d+)$", detail_comment, name="news-detail"),
]

gamebase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todolist/", include("dotolist.urls")),
    path("pcbuild/", include("pcbuild.urls")),
    path("", include("catalog.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.


class Genre(models.Model):
    name = models.CharField(
        max_length=50,
        help_text="Введите название жанра",
        verbose_name="Жанр игры",
    )

    def __str__(self):
        return self.name


class Game(models.Model):
    name = models.CharField(
        max_length=100,
        help_text="Введите название игры",
        verbose_name="Название игры",
    )
    release_date = models.DateField(
        help_text="Введите дату выхода игры",
        verbose_name="Дата выхода игры",
        null=True,
        blank=True,
    )
    picture = models.ImageField(upload_to="games/", default="...")

    genre = models.ForeignKey(
        "Genre",
        on_delete=models.CASCADE,
        help_text="Выберите жанр игры",
        verbose_name="Жанр игры",
        null=True,
        blank=True,
    )

    console = models.ForeignKey(
        "Console",
        on_delete=models.CASCADE,
        help_text="Выберите консоль",
        verbose_name="Консоль",
        null=True,
    )

    def __str__(self):
        return self.name


class Company(models.Model):
    name = models.CharField(
        max_length=50,
        help_text="Введите название компании",
        verbose_name="Название компании",
    )
    country = models.CharField(
        max_length=50,
        help_text="Введите страну компании",
        verbose_name="Страна",
    )

    logo = models.ImageField(upload_to="logo/", default="...")

    def __str__(self):
        return self.name


class Console(models.Model):
    name = models.CharField(
        max_length=50,
        help_text="Введите название консоли",
        verbose_name="Название консоли",
    )
    release_date = models.DateField(
        help_text="Введите дату выхода консоли",
        verbose_name="Дата выхода консоли",
        null=True,
        blank=True,
    )
    company = models.ForeignKey(
        "Company",
        on_delete=models.CASCADE,
        help_text="Выберите компанию",
        verbose_name="Компания",
        null=True,
    )
    photo = models.ImageField(upload_to="consoles/", default="...")

    text = models.TextField(
        help_text="Введите описание консоли",
        verbose_name="Описание консоли",
        null=True,
    )

    def get_absolute_url(self):
        return reverse("console-detail", args=[str(self.id)])

    def __str__(self):
        return self.name


class News(models.Model):
    name = models.CharField(
        max_length=50,
        help_text="Введите название консоли",
        verbose_name="Название консоли",
    )
    publish_date = models.DateField(auto_now_add=True)

    text = models.TextField(
        help_text="Введите описание консоли",
        verbose_name="Описание консоли",
        null=True,
        blank=True,
    )

    photo = models.ImageField(
        upload_to="news/",
        default="...",
        null=True,
        blank=True,
    )

    def get_absolute_url(self):
        return reverse("news-detail", args=[str(self.id)])

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = [
            "-pk",
        ]


class Comments(models.Model):
    # user = models.CharField(max_length=50, blank=True, null=True)
    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    text = models.CharField(max_length=300)

    date_time = models.DateTimeField(auto_now_add=True)

    news = models.ForeignKey(
        "News",
        on_delete=models.CASCADE,
    )


class SeriesOfPhotoShoots(models.Model):
    name = models.CharField(max_length=20)
    series_preview = models.CharField(max_length=20, primary_key=True, unique=True)


class PhotoOfPeople(models.Model):
    name = models.CharField(max_length=20)
    human = models.ForeignKey(
        "SeriesOfPhotoShoots",
        on_delete=models.CASCADE,
    )

catalog/forms.py
from turtle import textinput
from django import forms
from .models import News


class CommentForm(forms.Form):
    text = forms.CharField(
        label="Comment",
        max_length=300,
        widget=forms.Textarea(
            attrs={
                "class": "form-control",
                "rows": "3",
            }
        ),
    )


# class NewsForm(forms.Form):
#     name = forms.CharField(label="Заголовок", max_length=50)
#     text = forms.CharField(label="Текст", widget=forms.Textarea)
#     photo = forms.ImageField(label="Изображение")


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ["name", "text", "photo"]

    # widgets = {
    #     "name": forms.TextInput(attrs={"class": "form-control"}),
    #     "text": forms.Textarea(attrs={"class": "form-control", "rows": "10"}),
    #     "photo": forms.ImageField(attrs={"class": "form-control-file"}),
    # }
    def __init__(self, *args, **kwargs):
        super(NewsForm, self).__init__(*args, **kwargs)
        self.fields["name"].widget.attrs.update({"class": "form-control"})
        self.fields["text"].widget.attrs.update({"class": "form-control"})
        self.fields["text"].widget.attrs.update({"rows": "10"})
        self.fields["photo"].widget.attrs.update({"class": "form-control-file"})

catalog/views.py
from http.client import HTTPResponse
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Console, Company, News, Comments
from django.views import generic
from .forms import *
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.core.paginator import Paginator
from django.db.models import F

# Create your views here.
from .models import PhotoOfPeople, SeriesOfPhotoShoots


def index(request):
    news = News.objects.all()
    # paginator = Paginator()
    context = {"news": news}

    return render(request, "catalog/index.html", context)


def consoles(request):
    companys = Company.objects.all()
    consoles = Console.objects.all()
    print(SeriesOfPhotoShoots.objects.filter(photoofpeople=None))
    # print(SeriesOfPhotoShoots.objects.exclude(pk=F("photoofpeople")))
    # test = Company.objects.exclude(pk=F("console__company__id"))
    # print(F("console__company_id"))
    context = {
        "consoles": consoles,
        "companys": companys,
    }
    return render(request, "catalog/consoles.html", context)


def company_consoles(request, company_id):
    companys = Company.objects.all()
    consoles = Console.objects.filter(company=company_id)

    context = {
        "consoles": consoles,
        "companys": companys,
    }
    return render(request, "catalog/consoles.html", context)


def make_news(request):
    newsform = NewsForm()
    context = {"newsform": newsform}
    print(request.method)
    print(request.FILES)
    if request.method == "POST" and request.FILES:
        print("hello")
        name = request.POST.get("name")
        text = request.POST.get("text")
        photo = request.FILES["photo"]
        print(photo)
        news = News(name=name, text=text, photo=photo)
        news.save()
        return HttpResponseRedirect("/")
    return render(request, "catalog/make_news.html", context)


class ConsoleDetailView(generic.DetailView):
    model = Console


def detail_comment(request, pk):
    news = News.objects.get(pk=pk)
    comment_form = CommentForm()
    if request.method == "POST":
        user = request.user
        # name = request.POST.get("name")
        text = request.POST.get("text")
        comment = Comments(user=user, text=text, news=news)
        comment.save()
        return HttpResponseRedirect(reverse("news-detail", args=[pk]))
    else:
        context = {"comment_form": comment_form, "news": news}
        return render(request, "catalog/news_detail.html", context)


# class NewsDetailView(generic.DetailView):
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context["comment_form"] = CommentForm()
#         return context

#     def get(self, request, *args, **kwargs):

#         self.object = self.get_object()
#         context = self.get_context_data(object=self.object)
#         if request.method == "POST":
#             name = request.POST.get("name")
#             text = request.POST.get("text")
#             print(name, text)
#         return self.render_to_response(context)

#     model = News

templates/catalog/console_detail.html
{% extends 'base.html' %}

{% block content %}
<img src="{{console.photo.url}}" style="max-width: 100%; height: auto; display: block;" class="img-thumbnail" alt="...">
<p>{{ console.name }}</p>
<p>Компания: {{ console.company }}</p>

{% endblock content %}

templates/catalog/consoles.html
{% extends 'base.html' %}
{% block sidebar %}
<div class="col-sm-2">
  <h2>Компании</h2>

  {% if companys %}

  <div class="list-group">
    <a href="{% url 'consoles' %}" class="list-group-item list-group-item-action">Все</a>
    {% for company in companys %}
    <a href="{% url 'consoles' %}{{company.pk}}" class="list-group-item list-group-item-action">{{company.name}}</a>
    {% endfor %}
  </div>
  {% endif %}
</div>
{% endblock sidebar %}
{% block content %}
<div class="col-sm-10">
  <h2>Консоли</h2>
  {% if consoles %}
  <div class="container">
    <div class="row">

      {% for console in consoles %}
      <div class="col-sm-4">
        <div class="card" style="width: 18rem; margin: 5px;">
          <a href="{{console.get_absolute_url}}"><img src="{{console.photo.url}}"
              style="max-width: 100%; height: auto; display: block;" class="card-img-top img-thumbnail" alt="..."></a>
          <div class="card-body">
            <h5 class="card-title"><a href="{{console.get_absolute_url}}">{{console.name}}</a></h5>
            <p class="card-text">{{console.company}} Some quick example text to build on the card title and make up the
              bulk of the card's content.</p>

          </div>
        </div>
      </div>
      {% endfor %}
      {% endif %}

    </div>
  </div>

</div>

{% endblock content %}

templates/catalog/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Сайт Gamebase</h1>

<div class="row text-center">

  <div class="col">
    {% if user.is_authenticated %}
    <a href="{% url 'makenews' %}" class="btn btn-primary btn-block mb-3">Написать новость</a>
    {% else %}
    <p>Для создания новости необходимо войти в систему</p>
    {% endif %}
  </div>
</div>

{% for new in news %}
<div class="row justify-content-center">

  <div class="card mb-3" style="width: 32rem;">
    <img src="{{new.photo.url}}" class="card-img-top" width="300" height="200"
      style="object-fit: cover; object-position: middle;" alt="...">
    <div class="card-body">
      <h5 class="card-title">{{new.name}}</h5>
      <p class="card-text">{{ new.text|truncatechars:170 }}</p>
      <div class="container">
        <div class="row">
          <div class="col">
            <h2>{{new.pk}}</h2>
            <a href="{{ new.get_absolute_url }}" class="btn btn-primary">Read more</a>

          </div>
          <div class="col">
            <p>{{ new.publish_date }}</p>

          </div>
        </div>
      </div>
    </div>
    <a href="{{ new.get_absolute_url }}" class="stretched-link"></a>
  </div>
</div>
{% endfor %}

{% endblock content %}

templates/catalog/make_news.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ newsform.as_table }}
    </table>
    <input type="submit" value="Опубликовать">
</form>
{% endblock content %}

templates/catalog/news_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-6 mx-auto">
            <img src="{{news.photo.url}}" class="img-fluid rounded mx-auto d-block" alt="...">


            <h1>{{news.name}}</h1>
            <p class="text">{{news.text}}</p>

            <h4>Comments</h4>
            {% if news.comments_set.all %}
            {% for comment in news.comments_set.all %}
            <div class="card mb-2">
                <div class="card-body">
                    <div class="container">
                        <div class="row">
                            <div class="col"><strong>{{ comment.user }}</strong></div>
                            <div class="col">{{ comment.date_time|date:"H:i d.m.Y" }}</div>
                        </div>
                        <div class="row">
                            <p class="text-right">{{ comment.text }}</p>
                        </div>
                    </div>


                </div>
            </div>
            {% endfor %}
            {% endif %}
            <div class="card mb-2">
                <div class="card-body">
                    {% if user.is_authenticated %}
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ comment_form.as_p }}
                        <input type="submit" value="Submit" class="btn btn-secondary">
                    </form>
                    {% else %}
                    <p>Только авторизованные пользователи могут оставлять комментарии</p>
                    {% endif %}

                </div>
            </div>

        </div>
    </div>
</div>

{% endblock content %}